### ISSUE TITLE
test oracle v0.6

### ISSUE THREAD

**Issue by tmakatos** [nutanix/libvfio-user#295]

**Comment by tmakatos** [comment]
Getting interrupt info seems broken in the client: https://github.com/oracle/qemu/issues/2. This doesn't prevent the GPIO sample from running correctly, so it's fine for now.

**Comment by tmakatos** [comment]
I can create a guest normally via libvirt and then by trivially editing the XML file I can see the GPIO device (haven't trying to use it yet because the GPIO kernel module isn't readily available):
```
<domain type='qemu' ... xmlns:qemu='http://libvirt.org/schemas/domain/qemu/1.0'>
...
<emulator>/opt/qemu/bin/qemu-system-x86_64</emulator>
...
  <qemu:commandline>
    <qemu:arg value='-device'/>
    <qemu:arg value='vfio-user-pci,socket=/var/run/vfio-user.sock'/>
  </qemu:commandline>
</domain>
```

**Comment by tmakatos** [comment]
BTW JJ pushed v0.6 which includes `x-migration-enabled`.

**Comment by tmakatos** [comment]
GPIO works.

To live migrate the guest:
```
virsh migrate --live --verbose --copy-storage-all <guest name> qemu+ssh://<destination IP address>/system
```
Note that libvirt needs a working hostname for the destination host, which can be trivially solved by adding an entry to `/etc/hosts` on the source host.

**Comment by jlevon** [comment]
cool!

**Comment by tmakatos** [comment]
I've added the migration region and it still fails with the same error, so it must be something else in `vfio_migration_probe`, should be trivial to figure out what.

**Comment by tmakatos** [comment]
Update:
Used patch from Elena, the first `vfio_mig_read` now works, however the next `vfio_mig_write` fails with:
```
#0  __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:50
#1  0x00007f223292e535 in __GI_abort () at abort.c:79
#2  0x00007f22339b6dc3 in ?? () from target:/usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
#3  0x00007f2233a1067a in g_assertion_message_expr () from target:/usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
#4  0x000055eeba15c93b in qemu_mutex_unlock_iothread () at ../softmmu/cpus.c:492
#5  0x000055eeba1bdcd6 in vfio_user_send (proxy=0x55eebebe1d50, msg=0x7f20e3ffbcf0, fds=0x0) at ../hw/vfio/user.c:271
#6  0x000055eeba1bf5af in vfio_user_region_write (vbasedev=0x55eebebdbd40, index=9, offset=0, count=4, data=0x7f20e3ffbdec) at ../hw/vfio/user.c:867
#7  0x000055eeba1f88fa in vfio_mig_access (vbasedev=0x55eebebdbd40, val=0x7f20e3ffbdec, count=4, off=0, iswrite=true) at ../hw/vfio/migration.c:59
#8  0x000055eeba1f8a98 in vfio_mig_rw (vbasedev=0x55eebebdbd40, buf=0x7f20e3ffbdec "\003", count=4, off=0, iswrite=true) at ../hw/vfio/migration.c:94
#9  0x000055eeba1f8b8c in vfio_migration_set_state (vbasedev=0x55eebebdbd40, mask=7, value=2) at ../hw/vfio/migration.c:140
#10 0x000055eeba1f96d0 in vfio_save_setup (f=0x55eebd169120, opaque=0x55eebebdbd40) at ../hw/vfio/migration.c:478
#11 0x000055eeb9d248cf in qemu_savevm_state_setup (f=0x55eebd169120) at ../migration/savevm.c:1177
#12 0x000055eeb9df8a5c in migration_thread (opaque=0x55eebd029500) at ../migration/migration.c:3535
#13 0x000055eeba4b9514 in qemu_thread_start (args=0x55eebd1b3be0) at ../util/qemu-thread-posix.c:521
#14 0x00007f2232ad4fa3 in start_thread (arg=<optimized out>) at pthread_create.c:486
#15 0x00007f2232a054cf in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95
```
I'll try doing the same thing as in the patch in `vfio_user_send`.

**Comment by tmakatos** [comment]
Storing and restoring state (the value of the PIN) works.

**Comment by tmakatos** [comment]
GPIO live migration works, I'm tracking related problems in separate issues.
